// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHkYQRRygmtsggGJAbzg6m3QnAg5Gs8bQ',
    appId: '1:93027596899:web:e5b35ba66160efeb3ad656',
    messagingSenderId: '93027596899',
    projectId: 'drive-app-780b3',
    authDomain: 'drive-app-780b3.firebaseapp.com',
    storageBucket: 'drive-app-780b3.firebasestorage.app',
    measurementId: 'G-58SQJ0KG8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa-QY9hSN2iPBwVYS7OxiyTCX9_cGHS28',
    appId: '1:93027596899:android:29671dedcf6e3e3f3ad656',
    messagingSenderId: '93027596899',
    projectId: 'drive-app-780b3',
    storageBucket: 'drive-app-780b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzuHyq8_X28SI31ZzBhpGI_AedSPJIO5c',
    appId: '1:93027596899:ios:6d714692a87d1b143ad656',
    messagingSenderId: '93027596899',
    projectId: 'drive-app-780b3',
    storageBucket: 'drive-app-780b3.firebasestorage.app',
    iosBundleId: 'com.example.driverapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzuHyq8_X28SI31ZzBhpGI_AedSPJIO5c',
    appId: '1:93027596899:ios:6d714692a87d1b143ad656',
    messagingSenderId: '93027596899',
    projectId: 'drive-app-780b3',
    storageBucket: 'drive-app-780b3.firebasestorage.app',
    iosBundleId: 'com.example.driverapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHkYQRRygmtsggGJAbzg6m3QnAg5Gs8bQ',
    appId: '1:93027596899:web:5c5f6d3fa02c4aa93ad656',
    messagingSenderId: '93027596899',
    projectId: 'drive-app-780b3',
    authDomain: 'drive-app-780b3.firebaseapp.com',
    storageBucket: 'drive-app-780b3.firebasestorage.app',
    measurementId: 'G-CZTB9486SP',
  );
}
